version: "3.7"
networks:
  dev-network:
services:
  server:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    image: docker.pkg.github.com/utain/go-12factor-example/go-server:dev
    environment:
      DATABASE_URL: postgresql://example:P@55w0rd@postgres:5432/example?sslmode=disable
    ports:
      - "5000:5000"
    command: "go run ./cmd/server start"
    volumes:
      - ./:/app/
    networks:
      - dev-network
  postgres:
    image: postgres:12.1-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=P@55w0rd
      - POSTGRES_USER=example
      - POSTGRES_DB=example
    networks:
      - dev-network